version: "2.1"
services:
  steamos:
    # Use a pre-built image from Docker Hub
#    image: lscr.io/linuxserver/steamos:latest
    build: .
#      image : docker-steam
    container_name: steamos
    hostname: steamOs # optional
    privileged: true
    cap_add:
#      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined # optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DRINODE=/dev/dri/renderD129
#      - HOST_IP=192.168.1.10 # optional
      - STARTUP=KDE # optional
      - RESOLUTION=1366x768 # optional
      - ENABLE_SUNSHINE=false
    volumes:
      - /mnt/blockstore/steam/config:/config
      - /dev/input:/dev/input # optional
      - /mnt/blockstore/steam/data:/run/udev/data # optional
    network_mode: "host"
# Join netword Docker for steam remote play
#    ports:
#      - 3002:3000
#      - 3003:3001
#      - "27031-27036:27031-27036/udp" # optional (wrap the range in quotes)
#      - "27031-27037:27031-27037" # optional (wrap the range in quotes)
#      - "47984-47990:47984-47990" # optional (wrap the range in quotes)
#      - "48010-48010:48010-48010" # optional (wrap the range in quotes)
#      - "47998-48000:47998-48000/udp" # optional (wrap the range in quotes)
    devices:
      - /dev/dri/:/dev/dri/
    shm_size: "20gb"
    restart: unless-stopped
